package com.huami.watch.train.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.huami.watch.train.model.TrainRecord;

import com.huami.watch.train.model.TrainRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trainRecordDaoConfig;

    private final TrainRecordDao trainRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trainRecordDaoConfig = daoConfigMap.get(TrainRecordDao.class).clone();
        trainRecordDaoConfig.initIdentityScope(type);

        trainRecordDao = new TrainRecordDao(trainRecordDaoConfig, this);

        registerDao(TrainRecord.class, trainRecordDao);
    }
    
    public void clear() {
        trainRecordDaoConfig.getIdentityScope().clear();
    }

    public TrainRecordDao getTrainRecordDao() {
        return trainRecordDao;
    }

}
